// Deterministic execution loop. Drives a campaign through a small, testable
// sequence of tool calls. Every state change goes through the durable
// services so a restart can rehydrate without losing progress.

import {
  createBlocker,
  listOpenBlockers,
} from './services/blockers';
import {
  finishAttempt,
  startAttempt,
} from './services/attempts';
import {
  getCampaign,
  getPrimaryAgentId,
  setProgressSummary,
  setStatus,
} from './services/campaigns';
import { record } from './services/events';
import { listArtifacts } from './services/artifacts';
import { invokeTool } from './tools/registry';
import type { JsonValue } from '../../db/json';

type StepPlan = {
  name: string;
  tool: string;
  input: JsonValue;
};

function planForCampaign(name: string, objective: string | null): StepPlan[] {
  return [
    {
      name: 'Draft mission summary',
      tool: 'artifact.write',
      input: {
        title: 'mission-summary.md',
        artifactType: 'markdown',
        description: 'Initial summary of the campaign objective',
        content: [
          `# ${name}`,
          '',
          objective ?? '_(no objective provided)_',
          '',
          '_Generated by the durable engine._',
        ].join('\n'),
      },
    },
    {
      name: 'Record initial action log',
      tool: 'artifact.write',
      input: {
        title: 'action-log.md',
        artifactType: 'log',
        content: [
          '# Action Log',
          '',
          `- Engine started campaign \`${name}\``,
          '- Awaiting tool invocations',
        ].join('\n'),
      },
    },
  ];
}

const inflight = new Set<string>();

export async function runCampaign(campaignId: string): Promise<void> {
  if (inflight.has(campaignId)) return;
  inflight.add(campaignId);
  try {
    const campaign = await getCampaign(campaignId);
    if (!campaign) return;

    // `blocked` is intentionally excluded — resumption clears blockers via
    // `resumeCampaign` first, then re-enters this loop with a clear queue.
    const startable: ReadonlyArray<string> = ['draft', 'queued', 'approved', 'paused', 'running'];
    if (!startable.includes(campaign.status)) return;

    const openBlockers = await listOpenBlockers(campaignId);
    if (openBlockers.length > 0) {
      await setStatus(campaignId, 'blocked', `Cannot run — ${openBlockers.length} open blocker(s)`);
      return;
    }

    await setStatus(campaignId, 'running', 'Engine acquired campaign');

    const agentId = await getPrimaryAgentId(campaignId);
    const plan = planForCampaign(campaign.name, campaign.description);
    let stepsCompleted = 0;
    let blocked = false;

    for (const step of plan) {
      const attempt = await startAttempt({
        campaignId,
        agentId,
        executionMode: 'api',
        inputPayload: { tool: step.tool, input: step.input, step: step.name },
      });
      const outcome = await invokeTool(step.tool, step.input, {
        campaignId,
        agentId,
      });
      if (outcome.ok) {
        await finishAttempt(attempt.id, 'succeeded', outcome.output);
        stepsCompleted += 1;
      } else {
        await finishAttempt(attempt.id, 'failed', { tool: step.tool }, outcome.blocker.summary);
        await createBlocker({
          campaignId,
          createdByAgentId: agentId,
          summary: outcome.blocker.summary,
          details: outcome.blocker.details,
          severity: outcome.blocker.severity,
          attemptedMethod: outcome.blocker.attemptedMethod,
          failureEvidence: outcome.blocker.failureEvidence,
          requiredResolution: outcome.blocker.requiredResolution,
          canContinueElsewhere: outcome.blocker.canContinueElsewhere ?? false,
          status: 'open',
        });
        blocked = true;
        break;
      }

      const artifacts = await listArtifacts(campaignId);
      await setProgressSummary(campaignId, {
        progress: Math.min(0.99, stepsCompleted / plan.length),
        filesUpdated: artifacts.length,
        rowsProcessed: 0,
        batchCount: stepsCompleted,
      });
    }

    if (blocked) {
      await setStatus(campaignId, 'blocked', 'Engine paused on first blocker');
      return;
    }

    await setProgressSummary(campaignId, {
      progress: 1,
      filesUpdated: (await listArtifacts(campaignId)).length,
      rowsProcessed: 0,
      batchCount: stepsCompleted,
    });
    await setStatus(campaignId, 'completed', 'All planned steps succeeded');
  } finally {
    inflight.delete(campaignId);
  }
}

export async function resumeCampaign(campaignId: string): Promise<void> {
  // Resolve open blockers off the table first; the loop will re-check.
  const open = await listOpenBlockers(campaignId);
  for (const b of open) {
    await record(campaignId, 'blocker_resolved', `Operator-resumed; clearing blocker: ${b.summary}`, {
      blockerId: b.id,
    });
  }
  await runCampaign(campaignId);
}

export function isInflight(campaignId: string): boolean {
  return inflight.has(campaignId);
}
