
```tsx                                                                                                                                                                                                        
  "use client"                                                                                                                                                                                                
                                                                                                                                                                                                              
  import { useState } from "react"                                                                                                                                                                            
                                                                                                                                                                                                              
  export default function Iceman() {                                                                                                                                                                          
    const [input, setInput] = useState("")                                                                                                                                                                    
    const [messages, setMessages] = useState<{ role: string, text: string }[]>([])                                                                                                                            
                                                                                                                                                                                                              
    async function send() {                                                                                                                                                                                   
      if (!input.trim()) return                                                                                                                                                                               
                                                                                                                                                                                                              
      // Show the user's message immediately                                                                                                                                                                  
      setMessages([...messages, { role: "🧊 you", text: input }])                                                                                                                                             
                                                                                                                                                                                                              
      const res = await fetch("https://mother.nuriy.com/v1/responses", {                                                                                                                                      
        method: "POST",                                                                                                                                                                                       
        headers: {                                                                                                                                                                                            
          "Content-Type": "application/json",                                                                                                                                                                 
          "Authorization": "Bearer 8bcb9a096d688cd87406486da0c68e1a51708425975870bc",                                                                                                                         
          "x-openclaw-agent-id": "iceman"                                                                                                                                                                     
        },                                                                                                                                                                                                    
        body: JSON.stringify({                                                                                                                                                                                
          model: "openclaw",                                                                                                                                                                                  
          input: input                                                                                                                                                                                        
        })                                                                                                                                                                                                    
      })                                                                                                                                                                                                      
                                                                                                                                                                                                              
      const data = await res.json();                                                                                                                                                                          
      // Add the AI's reply                                                                                                                                                                                   
      setMessages(m =>                                                                                                                                                                                        
        [...m, { role: "🤖 iceman", text: data.output_text || "No reply from agent." }]                                                                                                                       
      )                                                                                                                                                                                                       
      setInput("")                                                                                                                                                                                            
    }                                                                                                                                                                                                         
                                                                                                                                                                                                              
    return (                                                                                                                                                                                                  
      <div style={{                                                                                                                                                                                           
        background: "#0b0f17",                                                                                                                                                                                
        minHeight: "100vh",                                                                                                                                                                                   
        width: "100%",                                                                                                                                                                                        
        display: "flex",                                                                                                                                                                                      
        flexDirection: "column",                                                                                                                                                                              
        alignItems: "stretch"                                                                                                                                                                                 
      }}>                                                                                                                                                                                                     
        <div style={{                                                                                                                                                                                         
          height: "70px",                                                                                                                                                                                     
          display: "flex",                                                                                                                                                                                    
          alignItems: "center",                                                                                                                                                                               
          paddingLeft: "24px",                                                                                                                                                                                
          fontSize: "22px",                                                                                                                                                                                   
          color: "white",                                                                                                                                                                                     
          background: "rgba(20,25,35,0.85)",                                                                                                                                                                  
          backdropFilter: "blur(12px)"                                                                                                                                                                        
        }}>                                                                                                                                                                                                   
          🧊 ICEMAN                                                                                                                                                                                           
          <span style={{                                                                                                                                                                                      
            marginLeft: "10px",                                                                                                                                                                               
            fontSize: "12px",                                                                                                                                                                                 
            opacity: 0.6                                                                                                                                                                                      
          }}>                                                                                                                                                                                                 
            Mothership Builder Interface                                                                                                                                                                      
          </span>                                                                                                                                                                                             
        </div>                                                                                                                                                                                                
                                                                                                                                                                                                              
        <div style={{                                                                                                                                                                                         
          flex: 1,                                                                                                                                                                                            
          padding: 24,                                                                                                                                                                                        
          display: "flex",                                                                                                                                                                                    
          flexDirection: "column",                                                                                                                                                                            
          gap: 16,                                                                                                                                                                                            
          color: "white"                                                                                                                                                                                      
        }}>                                                                                                                                                                                                   
          <div style={{                                                                                                                                                                                       
            background: "rgba(40,45,60,0.7)",                                                                                                                                                                 
            borderRadius: "8px",                                                                                                                                                                              
            padding: "24px",                                                                                                                                                                                  
            minHeight: "300px",                                                                                                                                                                               
            overflowY: "auto",                                                                                                                                                                                
            boxShadow: "0 2px 18px 0 #100f1e70"                                                                                                                                                               
          }}>                                                                                                                                                                                                 
            {messages.length === 0 ? (                                                                                                                                                                        
              <div style={{ opacity: 0.7 }}>                                                                                                                                                                  
                Type a message below & hit send to talk to Iceman.                                                                                                                                            
              </div>                                                                                                                                                                                          
            ) : (                                                                                                                                                                                             
              messages.map((m, i) => (                                                                                                                                                                        
                <div key={i} style={{                                                                                                                                                                         
                  marginBottom: "12px",                                                                                                                                                                       
                  borderBottom: "1px solid #2223",                                                                                                                                                            
                  paddingBottom: "6px"                                                                                                                                                                        
                }}>                                                                                                                                                                                           
                  <strong>{m.role}:</strong> {m.text}                                                                                                                                                         
                </div>                                                                                                                                                                                        
              ))                                                                                                                                                                                              
            )}                                                                                                                                                                                                
          </div>                                                                                                                                                                                              
          <div style={{ display: "flex", gap: 8 }}>                                                                                                                                                           
            <input                                                                                                                                                                                            
              value={input}                                                                                                                                                                                   
              onChange={e => setInput(e.target.value)}                                                                                                                                                        
              onKeyDown={e => { if (e.key === "Enter") send() }}                                                                                                                                              
              style={{                                                                                                                                                                                        
                flex: 1,                                                                                                                                                                                      
                padding: "11px 14px",                                                                                                                                                                         
                border: "none",                                                                                                                                                                               
                borderRadius: "4px",                                                                                                                                                                          
                background: "#232434",                                                                                                                                                                        
                color: "white",                                                                                                                                                                               
                fontSize: "18px"                                                                                                                                                                              
              }}                                                                                                                                                                                              
              autoFocus                                                                                                                                                                                       
              placeholder="Say something to Iceman…"                                                                                                                                                          
            />                                                                                                                                                                                                
            <button                                                                                                                                                                                           
              onClick={send}                                                                                                                                                                                  
              style={{                                                                                                                                                                                        
                background: "#38b8da",                                                                                                                                                                        
                color: "white",                                                                                                                                                                               
                fontSize: "18px",                                                                                                                                                                             
                border: "none",                                                                                                                                                                               
                borderRadius: "4px",                                                                                                                                                                          
                padding: "10px 18px",                                                                                                                                                                         
                cursor: "pointer"                                                                                                                                                                             
              }}>                                                                                                                                                                                             
              Send                                                                                                                                                                                            
            </button>                                                                                                                                                                                         
          </div>                                                                                                                                                                                              
        </div>                                                                                                                                                                                                
      </div>                                                                                                                                                                                                  
    )                                                                                                                                                                                                         
  }                                                                                                                                                                                                           
```                                                                                                                                                                                                           
                               
