ALTER TYPE "EmailTriageBucket" ADD VALUE IF NOT EXISTS 'ACT_SOON';
ALTER TYPE "EmailTriageBucket" ADD VALUE IF NOT EXISTS 'OPPORTUNITY_PILE';
ALTER TYPE "EmailTriageBucket" ADD VALUE IF NOT EXISTS 'NOT_YOUR_SPEED';
ALTER TYPE "EmailTriageBucket" ADD VALUE IF NOT EXISTS 'NEED_HUMAN_EYES';
ALTER TYPE "EmailTriageBucket" ADD VALUE IF NOT EXISTS 'RELATIONSHIP_KEEPER';
